apiVersion: infra.nephio.org/v1alpha1
kind: WorkloadCluster
metadata: # kpt-merge: /workload-cluster
  name: workload-cluster
  annotations:
    config.kubernetes.io/local-config: "true"
    kpt.dev/config-injection: required
    internal.kpt.dev/upstream-identifier: 'infra.nephio.org|WorkloadCluster|default|workload-cluster'
    kpt.dev/injected-resource: rke-core
spec:
  clusterName: rke-core
  cnis:
  - macvlan
  - ipvlan
  - sriov
  masterInterface: ens4
